apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-jenkins
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: nginx-jenkins
    spec:
      containers:
      - name: nginx
        image: wangyanglinux/myapp:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: nginx-data
          mountPath: /usr/share/nginx/html
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d


      volumes:
      - name: nginx-data
        nfs:
          path: /nfs4/data
          server: 192.168.0.214
      - name: nginx-conf
        nfs:
          path: /nfs4/nginx-conf
          server: 192.168.0.214
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-jenkins
spec:
  type: NodePort
  ports:
  - port: 80
    name: web
    targetPort: 80
    protocol: TCP
    nodePort: 30900
  selector:
    name: nginx-jenkins
